---
- name: install java
  hosts: all
  become: true
  roles:
    - role: kafka-opdk-java

- name: install zookeeper
  hosts: zookeeper
  become: true
  roles:
    - role: kafka-opdk-zookeeper

- name: install kafka broker
  hosts: kafka_broker
  become: true
  roles:
    - role: kafka-opdk-installer